title: "Dev Mateus Cardoso"
email: dev.mateuscardoso@gmail.com
description: "My presentation page as a full stack developer"
baseurl: "/me"
url: "https://matecardoso.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
github_username: matecardoso
